[package]
name = "netinfo"
version = "0.1.0"
edition = "2024"

[lib]
name = "netinfo"
path = "src/lib.rs"
crate-type = ["rlib"]

[target.'cfg(target_os = "windows")'.dependencies]
dunce = "1.0"

[dependencies]
netstat2 = "0.11.2"
local-ip-address = "0.6.5"
anyhow = "1.0"
