[package]
name = "tcping"
description = "🛠️ tcping-rs: Rust (rs) TCP Ping (tcping) Utility for Port Reachability."
version = "1.2.19"
edition = "2024"
license = "MIT"
authors = ["lvillis<lvillis@outlook.com>"]
repository = "https://github.com/lvillis/tcping-rs"
homepage = "https://github.com/lvillis/tcping-rs"
documentation = "https://github.com/lvillis/tcping-rs/blob/main/README.md"

[lib]
name = "tcping"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
clap = { version = "4.5.49", default-features = false, features = ["std", "color", "usage", "help", "suggestions", "error-context", "derive"] }
tokio = { version = "1.47.1", default-features = false, features = ["rt-multi-thread", "macros", "net", "time", "signal"] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.145", default-features = false, features = ["std"] }
thiserror = "2.0.17"
anyhow = "1.0.100"

